// <auto-generated />
namespace IdentityDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class alteracaoDeNome : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteracaoDeNome));
        
        string IMigrationMetadata.Id
        {
            get { return "201507161636524_alteracaoDeNome"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
